# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE_TYPE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - plugin
  - ruling
  - performancing

SQ_VERSION:
  - LTS
  - 5.2
  - 5.3
  - DEV
  - LATEST_RELEASE



exclude:
#exclude plugin tests on performance slaves
  - TEST: plugin
    SLAVE_TYPE: performance
    SQ_VERSION: LTS
  - TEST: plugin
    SLAVE_TYPE: performance
    SQ_VERSION: 5.2
  - TEST: plugin
    SLAVE_TYPE: performance
    SQ_VERSION: 5.3
  - TEST: plugin
    SLAVE_TYPE: performance
    SQ_VERSION: DEV
  - TEST: plugin
    SLAVE_TYPE: performance
    SQ_VERSION: LATEST_RELEASE
#exclude plugin tests on windows except for LATEST_RELEASE
  - TEST: plugin
    SLAVE_TYPE: windows
    SQ_VERSION: LATEST_RELEASE
#exclude ruling tests on performance slaves
  - TEST: ruling
    SLAVE_TYPE: performance
    SQ_VERSION: LTS
  - TEST: ruling
    SLAVE_TYPE: performance
    SQ_VERSION: 5.2
  - TEST: ruling
    SLAVE_TYPE: performance
    SQ_VERSION: 5.3
  - TEST: ruling
    SLAVE_TYPE: performance
    SQ_VERSION: DEV
  - TEST: ruling
    SLAVE_TYPE: performance
    SQ_VERSION: LATEST_RELEASE
#exclude all ruling jobs other than on LATEST_RELEASE on linux
  - TEST: ruling
    SLAVE_TYPE: linux
    SQ_VERSION: LTS
  - TEST: ruling
    SLAVE_TYPE: linux
    SQ_VERSION: 5.2
  - TEST: ruling
    SLAVE_TYPE: linux
    SQ_VERSION: 5.3
  - TEST: ruling
    SLAVE_TYPE: linux
    SQ_VERSION: DEV
#exclude all ruling jobs other than on LATEST_RELEASE on windows
  - TEST: ruling
    SLAVE_TYPE: windows
    SQ_VERSION: LTS
  - TEST: ruling
    SLAVE_TYPE: windows
    SQ_VERSION: 5.2
  - TEST: ruling
    SLAVE_TYPE: windows
    SQ_VERSION: 5.3
  - TEST: ruling
    SLAVE_TYPE: windows
    SQ_VERSION: DEV
#exclude all performances jobs on linux slaves
  - TEST: performancing
    SLAVE_TYPE: linux
    SQ_VERSION: LTS
  - TEST: performancing
    SLAVE_TYPE: linux
    SQ_VERSION: 5.2
  - TEST: performancing
    SLAVE_TYPE: linux
    SQ_VERSION: 5.3
  - TEST: performancing
    SLAVE_TYPE: linux
    SQ_VERSION: DEV
  - TEST: performancing
    SLAVE_TYPE: linux
    SQ_VERSION: LATEST_RELEASE
#exclude all performances jobs on windows slaves
  - TEST: performancing
    SLAVE_TYPE: windows
    SQ_VERSION: LTS
  - TEST: performancing
    SLAVE_TYPE: windows
    SQ_VERSION: 5.2
  - TEST: performancing
    SLAVE_TYPE: windows
    SQ_VERSION: 5.3
  - TEST: performancing
    SLAVE_TYPE: windows
    SQ_VERSION: DEV
  - TEST: performancing
    SLAVE_TYPE: windows
    SQ_VERSION: LATEST_RELEASE
#exclude all performances jobs other than on LATEST_RELEASE
  - TEST: performancing
    SLAVE_TYPE: performance
    SQ_VERSION: LTS
  - TEST: performancing
    SLAVE_TYPE: performance
    SQ_VERSION: 5.2
  - TEST: performancing
    SLAVE_TYPE: performance
    SQ_VERSION: 5.3
  - TEST: performancing
    SLAVE_TYPE: performance
    SQ_VERSION: DEV
