version: 1.0.{build}

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - git submodule update --init --recursive
  - set MAVEN_VERSION=3.2.5
  - choco install maven -version %MAVEN_VERSION%
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin
  - set JAVA_HOME=C:\Program Files\Java\jdk1.7.0

environment:
  matrix:
  - RUN: ruling
    SQ_VERSION: LATEST_RELEASE
  - RUN: its
    SQ_VERSION: DEV
  - RUN: ci
  - RUN: its
    SQ_VERSION: LTS_OR_OLDEST_COMPATIBLE

matrix:
  fast_finish: true

build_script:
  - ps: ./appveyor.ps1

test: off
